language: node_js

node_js:
  - "8"

services:
  - mongodb
  - redis-server
  
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - yarn test

after_success:
  - yarn coverage
